version: '3.1'

services:
  nginx:
    image: nginx:alpine
    deploy: # docker compose will ignore this, only apply to docker stack deploy
      placement:
        constraints:
          - node.hostname == "dockerhost8"
      replicas: 5
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 2s